server:
  port: 9000

spring:
  application:
    name: BOOK-API
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update